INSERT INTO Articles(writer_id, title) VALUES ('1', 'WFS');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Transportation Management');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Customer Engagement');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'ICD-9-CM');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'AKTA');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'FCIP');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'mTAB');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'NRI Services');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'UEFI');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'JNDI');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Charitable Giving');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Banking');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Payment by Results');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Administration');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'DFSS Green Belt');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'RCMS');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Juvederm');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'EIGRP');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'TMMi');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Two-phase Flow');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'HP QTP');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'PTT');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'QMF');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'WF');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'SBA');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Smartboard');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'RS Means');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Security Awareness');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'HMI Configuration');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Global Health');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Insurance');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Multilingual');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Architectural Design');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Crystal Reports');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Cross-functional Coordination');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Mycobacteriology');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Retirement Planning');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'ALM');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'EES');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'CNC');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Pharmaceutics');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Lymphoma');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Titration');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Tax Advisory');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'GMRA');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'TMG');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'DB2');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'VMware Infrastructure');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Guest Service Management');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Owners Representative');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Gnome');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'WS-*');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Zultys');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'RDO');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'RHEL');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Branding &amp; Identity');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'USDA Rural Housing');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Security Operations');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Karl Fisher');
INSERT INTO Articles(writer_id, title) VALUES ('1', '.htaccess');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'HCM Processes &amp; Forms');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'DCM');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'SDL');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'MFR');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'VTS');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Health Promotion');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Teaching');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'CCNP Certified');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Hyperion Reports');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'GSM-R');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Gastroenterology');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'JBuilder');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'TV Distribution');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Group Dynamics');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Sea Kayaking');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Nielsen Data');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Shotokan Karate');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Venipuncture');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Real Estate Development');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Screening Resumes');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Breaking News');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Plant Identification');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Product Life Cycle');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Mental Health');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Psychological Assessment');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'JSA');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'QMF');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Personal Training');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Data Quality');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'LUSAS');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Immunohistochemistry');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Benefits Negotiation');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Volunteering');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Dutch');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Awareness Raising');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'FDM');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'European Integration');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Cash Flow');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'Image Manipulation');
INSERT INTO Articles(writer_id, title) VALUES ('1', 'ATM Networks');
